apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-argocd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kube-argocd
  template:
    metadata:
      labels:
        app: kube-argocd
    spec:
      containers:
        - name: kube-argocd-container
          image: lbdevopscti/kube-argocd:34594ff4603cf4372c245bb413a7351be2d55d42
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kube-argocd-service
spec:
  selector:
    app: kube-argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
