name: Build and Deploy Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #   - name: Lint with flake8
      #     run: |
      #       # stop the build if there are Python syntax errors or undefined names
      #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #       # NOTE: Ignore E501 line too long
      #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=E501

      #   - name: Test with pytest
      #     run: |
      #       pip install pytest
      #       pytest tests

      - name: Build Docker image
        run: docker build -t kube-argocd:${{ github.sha }} .

      - name: Push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag kube-argocd:${{ github.sha }} ${{ secrets.DOCKER_REGISTRY }}/kube-argocd:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/kube-argocd:${{ github.sha }}

      - name: Update deployment YAML
        run: sed -i "s/{{TAG}}/${{ github.sha }}/g" deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deployment.yaml
          git commit -m "Update image tag to ${GITHUB_SHA}"
          git push origin main
